[project]
name = "poc08"
version = "0.1.0"
description = "See README"
readme = "README.md"
authors = [
    { name = "righettod", email = "dominique.righetto@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "httpx>=0.28.1",
    "langchain>=1.4.2",
    "langchain-core>=1.6.3",
    "langgraph>=1.2.11",
    "pydantic>=2.13.5",
]

[project.scripts]
poc08 = "poc08:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
