spring.application.name=poc-llm-mcp-server
debug=false
spring.main.banner-mode=off
logging.pattern.console=[%-5level] %msg%n
server.port=8081
###
# Properties for the MCP Server Configuration
# See https://docs.spring.io/spring-ai/reference/api/mcp/mcp-server-boot-starter-docs.html#_configuration_properties
spring.ai.mcp.server.stdio=false
spring.ai.mcp.server.type=SYNC
spring.ai.mcp.server.name=mcp-server
spring.ai.mcp.server.version=1.0.0
spring.ai.mcp.server.instructions=This server manages a data provider services.
spring.ai.mcp.server.capabilities.tool=true
spring.ai.mcp.server.capabilities.resource=false
spring.ai.mcp.server.capabilities.prompt=false
spring.ai.mcp.server.capabilities.completion=false
spring.ai.mcp.server.request-timeout=240
## Message interaction endpoint
spring.ai.mcp.server.sse-message-endpoint=/mcp/message
## SSE handshake/streaming endpoint
spring.ai.mcp.server.sse-endpoint=/mcp/transport
