debug=false
spring.application.name=poc
spring.main.banner-mode=off
logging.pattern.console=%-5level - %msg%n
logging.level.dev.langchain4j=DEBUG
ollama.baseurl=http://localhost:11434/
ollama.trace.exchanges=false
ollama.model.name=llama3.1:latest
ollama.model.temperature=0.0
ollama.model.response.timeout=240