#debug=false
spring.application.name=poc
spring.main.banner-mode=off
logging.pattern.console=%-5level - %msg%n
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG
# MCP Server Properties
# See https://docs.spring.io/spring-ai/reference/2.0-SNAPSHOT/api/mcp/mcp-stdio-sse-server-boot-starter-docs.html#_configuration_properties
spring.ai.mcp.server.enabled=true
spring.ai.mcp.server.tool-callback-converter=true
spring.ai.mcp.server.stdio=false
spring.ai.mcp.server.name=mcp-server
spring.ai.mcp.server.version=1.0.0
spring.ai.mcp.server.type=SYNC
spring.ai.mcp.server.capabilities.tool=true
spring.ai.mcp.server.capabilities.resource=true
spring.ai.mcp.server.capabilities.prompt=true
spring.ai.mcp.server.capabilities.completion=true
spring.ai.mcp.server.instructions=Sample MCP Server
spring.ai.mcp.server.annotation-scanner.enabled=true
## Protocol enablement
### Must be set to SSE or be blank to enable the Server Side Event server
### Must be set to STREAMABLE to enable the streamable server
### Only one protocol can be enab
spring.ai.mcp.server.protocol=STREAMABLE
## SSE endpoints properties
spring.ai.mcp.server.sse-message-endpoint=/mcp/messages
spring.ai.mcp.server.sseendpoint=/sse
## Streamable-HTTP endpoint properties
spring.ai.mcp.server.streamable-http.mcp-endpoint=/mcp

