name: Check POCs state
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
    - "poc*/**" 
  pull_request:
    branches: [ "main" ]
    paths:
    - "poc*/**"
permissions: read-all     
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Install system requirements
      run: sudo apt-get update -y && sudo apt-get install -y dos2unix
    - name: Install JDK 21
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Check
      run: dos2unix check-pocs-state.sh; chmod +x check-pocs-state.sh; bash check-pocs-state.sh
